spring:
  application:
    name: restApiTest
  datasource:
    url: jdbc:mysql://localhost:3306/restApiDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: restApi
    password: restApi
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

